### ISSUE TITLE
Epic: Drug Interaction MVP

### ISSUE THREAD

**Issue by icorbrey** [indiana-tech-software-engineering/drug-drug-interaction#10]
* [ ] Feature: Testing for drug interaction presence
* [ ] Feature: Querying the specific drug interactions of two drugs
* [ ] Feature: Querying the specific drug interactions of three or more drugs
